// Code generated by protoc-gen-go.
// source: libre.proto
// DO NOT EDIT!

/*
Package libre is a generated protocol buffer package.

It is generated from these files:
	libre.proto

It has these top-level messages:
	Empty
	SearchRequest
	SearchReply
	DeleteBookRequest
	SaveBookReply
	SaveBookRequest
	FetchBooksReply
	Book
	Identifier
	ImageLink
*/
package libre

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SearchRequest struct {
	Keyword string `protobuf:"bytes,1,opt,name=keyword" json:"keyword,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SearchReply struct {
	Books []*Book `protobuf:"bytes,1,rep,name=books" json:"books,omitempty"`
}

func (m *SearchReply) Reset()                    { *m = SearchReply{} }
func (m *SearchReply) String() string            { return proto.CompactTextString(m) }
func (*SearchReply) ProtoMessage()               {}
func (*SearchReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SearchReply) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type DeleteBookRequest struct {
	Book *Book `protobuf:"bytes,1,opt,name=book" json:"book,omitempty"`
}

func (m *DeleteBookRequest) Reset()                    { *m = DeleteBookRequest{} }
func (m *DeleteBookRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteBookRequest) ProtoMessage()               {}
func (*DeleteBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DeleteBookRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type SaveBookReply struct {
	Book *Book `protobuf:"bytes,1,opt,name=book" json:"book,omitempty"`
}

func (m *SaveBookReply) Reset()                    { *m = SaveBookReply{} }
func (m *SaveBookReply) String() string            { return proto.CompactTextString(m) }
func (*SaveBookReply) ProtoMessage()               {}
func (*SaveBookReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SaveBookReply) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type SaveBookRequest struct {
	Book *Book `protobuf:"bytes,1,opt,name=book" json:"book,omitempty"`
}

func (m *SaveBookRequest) Reset()                    { *m = SaveBookRequest{} }
func (m *SaveBookRequest) String() string            { return proto.CompactTextString(m) }
func (*SaveBookRequest) ProtoMessage()               {}
func (*SaveBookRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SaveBookRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type FetchBooksReply struct {
	Books []*Book `protobuf:"bytes,1,rep,name=books" json:"books,omitempty"`
}

func (m *FetchBooksReply) Reset()                    { *m = FetchBooksReply{} }
func (m *FetchBooksReply) String() string            { return proto.CompactTextString(m) }
func (*FetchBooksReply) ProtoMessage()               {}
func (*FetchBooksReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FetchBooksReply) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type Book struct {
	Id                  int64         `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title               string        `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	SubTitle            string        `protobuf:"bytes,3,opt,name=sub_title,json=subTitle" json:"sub_title,omitempty"`
	PublishedDate       string        `protobuf:"bytes,4,opt,name=published_date,json=publishedDate" json:"published_date,omitempty"`
	Description         string        `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Authors             []string      `protobuf:"bytes,6,rep,name=authors" json:"authors,omitempty"`
	IndustryIdentifiers []*Identifier `protobuf:"bytes,7,rep,name=industry_identifiers,json=industryIdentifiers" json:"industry_identifiers,omitempty"`
	ImageLinks          *ImageLink    `protobuf:"bytes,8,opt,name=image_links,json=imageLinks" json:"image_links,omitempty"`
}

func (m *Book) Reset()                    { *m = Book{} }
func (m *Book) String() string            { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()               {}
func (*Book) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Book) GetIndustryIdentifiers() []*Identifier {
	if m != nil {
		return m.IndustryIdentifiers
	}
	return nil
}

func (m *Book) GetImageLinks() *ImageLink {
	if m != nil {
		return m.ImageLinks
	}
	return nil
}

type Identifier struct {
	Type       string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Identifier string `protobuf:"bytes,2,opt,name=identifier" json:"identifier,omitempty"`
}

func (m *Identifier) Reset()                    { *m = Identifier{} }
func (m *Identifier) String() string            { return proto.CompactTextString(m) }
func (*Identifier) ProtoMessage()               {}
func (*Identifier) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type ImageLink struct {
	SmallThumbnail string `protobuf:"bytes,1,opt,name=small_thumbnail,json=smallThumbnail" json:"small_thumbnail,omitempty"`
	Thumbnail      string `protobuf:"bytes,2,opt,name=thumbnail" json:"thumbnail,omitempty"`
}

func (m *ImageLink) Reset()                    { *m = ImageLink{} }
func (m *ImageLink) String() string            { return proto.CompactTextString(m) }
func (*ImageLink) ProtoMessage()               {}
func (*ImageLink) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*Empty)(nil), "libre.Empty")
	proto.RegisterType((*SearchRequest)(nil), "libre.SearchRequest")
	proto.RegisterType((*SearchReply)(nil), "libre.SearchReply")
	proto.RegisterType((*DeleteBookRequest)(nil), "libre.DeleteBookRequest")
	proto.RegisterType((*SaveBookReply)(nil), "libre.SaveBookReply")
	proto.RegisterType((*SaveBookRequest)(nil), "libre.SaveBookRequest")
	proto.RegisterType((*FetchBooksReply)(nil), "libre.FetchBooksReply")
	proto.RegisterType((*Book)(nil), "libre.Book")
	proto.RegisterType((*Identifier)(nil), "libre.Identifier")
	proto.RegisterType((*ImageLink)(nil), "libre.ImageLink")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion3

// Client API for Libre service

type LibreClient interface {
	FetchBooks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FetchBooksReply, error)
	SaveBook(ctx context.Context, in *SaveBookRequest, opts ...grpc.CallOption) (*SaveBookReply, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error)
	DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*Empty, error)
}

type libreClient struct {
	cc *grpc.ClientConn
}

func NewLibreClient(cc *grpc.ClientConn) LibreClient {
	return &libreClient{cc}
}

func (c *libreClient) FetchBooks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FetchBooksReply, error) {
	out := new(FetchBooksReply)
	err := grpc.Invoke(ctx, "/libre.Libre/FetchBooks", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libreClient) SaveBook(ctx context.Context, in *SaveBookRequest, opts ...grpc.CallOption) (*SaveBookReply, error) {
	out := new(SaveBookReply)
	err := grpc.Invoke(ctx, "/libre.Libre/SaveBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libreClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchReply, error) {
	out := new(SearchReply)
	err := grpc.Invoke(ctx, "/libre.Libre/Search", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libreClient) DeleteBook(ctx context.Context, in *DeleteBookRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/libre.Libre/DeleteBook", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Libre service

type LibreServer interface {
	FetchBooks(context.Context, *Empty) (*FetchBooksReply, error)
	SaveBook(context.Context, *SaveBookRequest) (*SaveBookReply, error)
	Search(context.Context, *SearchRequest) (*SearchReply, error)
	DeleteBook(context.Context, *DeleteBookRequest) (*Empty, error)
}

func RegisterLibreServer(s *grpc.Server, srv LibreServer) {
	s.RegisterService(&_Libre_serviceDesc, srv)
}

func _Libre_FetchBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibreServer).FetchBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/libre.Libre/FetchBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibreServer).FetchBooks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Libre_SaveBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibreServer).SaveBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/libre.Libre/SaveBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibreServer).SaveBook(ctx, req.(*SaveBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Libre_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibreServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/libre.Libre/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibreServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Libre_DeleteBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibreServer).DeleteBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/libre.Libre/DeleteBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibreServer).DeleteBook(ctx, req.(*DeleteBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Libre_serviceDesc = grpc.ServiceDesc{
	ServiceName: "libre.Libre",
	HandlerType: (*LibreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchBooks",
			Handler:    _Libre_FetchBooks_Handler,
		},
		{
			MethodName: "SaveBook",
			Handler:    _Libre_SaveBook_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Libre_Search_Handler,
		},
		{
			MethodName: "DeleteBook",
			Handler:    _Libre_DeleteBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: fileDescriptor0,
}

func init() { proto.RegisterFile("libre.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x6e, 0x7e, 0x9c, 0x9f, 0x31, 0x49, 0xe8, 0x10, 0xa1, 0x55, 0x40, 0x10, 0x2c, 0x21, 0xca,
	0xa5, 0x2a, 0x21, 0xe2, 0xc0, 0x09, 0xa1, 0x80, 0x84, 0xd4, 0x93, 0xdb, 0x7b, 0x64, 0xc7, 0x03,
	0x5e, 0xd9, 0xf1, 0x1a, 0xef, 0x1a, 0xe4, 0x07, 0xe2, 0xd9, 0x78, 0x0d, 0xe4, 0xdd, 0x75, 0x1c,
	0xd2, 0x43, 0x7b, 0xf3, 0x7c, 0x3f, 0x33, 0x9e, 0xd9, 0x19, 0x70, 0x53, 0x1e, 0x16, 0x74, 0x99,
	0x17, 0x42, 0x09, 0x74, 0x74, 0xe0, 0x0d, 0xc1, 0xf9, 0xb2, 0xcf, 0x55, 0xe5, 0xbd, 0x85, 0xc9,
	0x0d, 0x05, 0xc5, 0x2e, 0xf6, 0xe9, 0x67, 0x49, 0x52, 0x21, 0x83, 0x61, 0x42, 0xd5, 0x6f, 0x51,
	0x44, 0xac, 0xb3, 0xec, 0x5c, 0x8c, 0xfd, 0x26, 0xf4, 0xae, 0xc0, 0x6d, 0xa4, 0x79, 0x5a, 0xe1,
	0x2b, 0x70, 0x42, 0x21, 0x12, 0xc9, 0x3a, 0xcb, 0xde, 0x85, 0xbb, 0x72, 0x2f, 0x4d, 0x99, 0xcf,
	0x42, 0x24, 0xbe, 0x61, 0xbc, 0x35, 0x9c, 0x6f, 0x28, 0x25, 0x45, 0x1a, 0xb4, 0x05, 0x5e, 0x42,
	0xbf, 0x66, 0x75, 0xf6, 0x13, 0x9b, 0x26, 0xbc, 0x2b, 0x98, 0xdc, 0x04, 0xbf, 0xac, 0xa7, 0xae,
	0x74, 0xaf, 0x63, 0x05, 0xb3, 0xd6, 0xf1, 0xc0, 0x2a, 0x6b, 0x98, 0x7d, 0x25, 0xb5, 0x8b, 0x6b,
	0x48, 0x3e, 0xb8, 0xa3, 0x3f, 0x5d, 0xe8, 0xd7, 0x31, 0x4e, 0xa1, 0xcb, 0xcd, 0x84, 0x7a, 0x7e,
	0x97, 0x47, 0x38, 0x07, 0x47, 0x71, 0x95, 0x12, 0xeb, 0xea, 0xa1, 0x99, 0x00, 0x9f, 0xc1, 0x58,
	0x96, 0xe1, 0xd6, 0x30, 0x3d, 0xcd, 0x8c, 0x64, 0x19, 0xde, 0x6a, 0xf2, 0x35, 0x4c, 0xf3, 0x32,
	0x4c, 0xb9, 0x8c, 0x29, 0xda, 0x46, 0x81, 0x22, 0xd6, 0xd7, 0x8a, 0xc9, 0x01, 0xdd, 0x04, 0x8a,
	0x70, 0x09, 0x6e, 0x44, 0x72, 0x57, 0xf0, 0x5c, 0x71, 0x91, 0x31, 0x47, 0x6b, 0x8e, 0xa1, 0xfa,
	0xc9, 0x82, 0x52, 0xc5, 0xa2, 0x90, 0x6c, 0xb0, 0xec, 0xd5, 0x4f, 0x66, 0x43, 0xdc, 0xc0, 0x9c,
	0x67, 0x51, 0x29, 0x55, 0x51, 0x6d, 0x79, 0x44, 0x99, 0xe2, 0xdf, 0x39, 0x15, 0x92, 0x0d, 0x75,
	0x83, 0xe7, 0xb6, 0xc1, 0x6f, 0x07, 0xc6, 0x7f, 0xd2, 0xc8, 0x5b, 0x4c, 0xe2, 0x3b, 0x70, 0xf9,
	0x3e, 0xf8, 0x41, 0xdb, 0x94, 0x67, 0x89, 0x64, 0x23, 0x3d, 0xd2, 0xc7, 0x8d, 0xb9, 0x66, 0xae,
	0x79, 0x96, 0xf8, 0xc0, 0x9b, 0x4f, 0xe9, 0x7d, 0x02, 0x68, 0x33, 0x20, 0x42, 0x5f, 0x55, 0x39,
	0xd9, 0x85, 0xd2, 0xdf, 0xf8, 0x02, 0xa0, 0xfd, 0x23, 0x3b, 0xb5, 0x23, 0xc4, 0xf3, 0x61, 0x7c,
	0x48, 0x8d, 0x6f, 0x60, 0x26, 0xf7, 0x41, 0x9a, 0x6e, 0x55, 0x5c, 0xee, 0xc3, 0x2c, 0xe0, 0xa9,
	0xcd, 0x35, 0xd5, 0xf0, 0x6d, 0x83, 0xe2, 0x73, 0x18, 0xb7, 0x12, 0x93, 0xb4, 0x05, 0x56, 0x7f,
	0x3b, 0xe0, 0x5c, 0xd7, 0x7f, 0x8d, 0x6b, 0x80, 0xf6, 0xf5, 0xf1, 0x91, 0xed, 0x45, 0x9f, 0xc4,
	0xe2, 0xa9, 0x8d, 0x4e, 0xd6, 0xc3, 0x3b, 0xc3, 0x8f, 0x30, 0x6a, 0xf6, 0x0c, 0x1b, 0xd5, 0xc9,
	0xe2, 0x2d, 0xe6, 0x77, 0x70, 0xe3, 0x5d, 0xc3, 0xc0, 0x5c, 0x0f, 0x1e, 0x14, 0xc7, 0x77, 0xb7,
	0xc0, 0x13, 0xd4, 0xb8, 0x3e, 0x00, 0xb4, 0x17, 0x84, 0xcc, 0x6a, 0xee, 0x1c, 0xd5, 0xe2, 0xbf,
	0x0e, 0xbc, 0xb3, 0x70, 0xa0, 0xaf, 0xfd, 0xfd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x80,
	0xf6, 0xf5, 0xfc, 0x03, 0x00, 0x00,
}
